### ISSUE TITLE
Not mirroring Fedora 30

### ISSUE THREAD

**Issue by ondrejsojka** [miabbott/piratemirror#1]
As far as I know, this is still the only european mirror for Fedora Silverblue. Would it be possible to mirror the objects from Fedora 30 too?

Thanks!

**Comment by miabbott** [comment]
There is new Fedora infrastructure in place that should improve download speeds for all users.

If you have the `fedora-repos-ostree` package installed on your host (should be included with most recent updates to SB 29 and SB 30), you'll have a new `fedora` remote defined like so:

```
$ cat /etc/ostree/remotes.d/fedora.conf 
[remote "fedora"]
url=https://ostree.fedoraproject.org
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/
contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist
```

Could you try using this remote and see if your speeds are fast enough?  I was considering disabling my mirror now that this new infra is in place.

**Comment by ondrejsojka** [comment]
Whoa! I had to follow instructions here
<https://discussion.fedoraproject.org/t/improved-upgrade-speeds-now-possible/1060>,
but in the end was able to fix the issue and am now getting download speeds
upwards of 10 MB/s. I think you can disable this mirror.

út 4. 6. 2019 v 16:03 odesílatel Micah Abbott <notifications@github.com>
napsal:

**Comment by miabbott** [comment]
Glad it worked for you!
